### PR TITLE
Added tutorial 8

### PR DESCRIPTION
**Pull request by simongravelle**
The tutorial follows:
- 1) mixing.lmp : placing nylon and CNT in the same box and equilibrating it in NPT
- 2) reacting.lmp : making the nylon react and recording the amount of water molecules in time

### CODE REVIEW

**Comment by simongravelle** [comment]
On the side note, with the last stable version of LAMMPS, I got the error:

- ERROR: Invalid range string: c2

I did not look into yet, but may be the origine of the error is obvious to you?

**Comment by jrgissing** [comment]
@simongravelle I am unable to reproduce the error using the LAMMPS 'stable' branch (29 Aug 2024), with either the current mixing.lmp or reacting.lmp input files in this PR

**Comment by jrgissing** [comment]
by the way, this tutorial is looking great. I am taking a closer look and will probably have some suggestions. For example, do you think it would be better if we used a single periodic CNT? I think I added an example of this in examples/replicate that I can adapt

**Comment by simongravelle** [comment]
> by the way, this tutorial is looking great. I am taking a closer look and will probably have some suggestions. For example, do you think it would be better if we used a single periodic CNT? I think I added an example of this in examples/replicate that I can adapt

My idea with having a dispersed suspension of CNT was that we could then perform tests on the final polymer/CNT mixture, or simply make a measurement of the adsorption or the polymer and the water within the CNTs. What would be the advantage to have a single periodic CNT?

**Comment by simongravelle** [comment]
> @simongravelle I am unable to reproduce the error using the LAMMPS 'stable' branch (29 Aug 2024), with either the current mixing.lmp or reacting.lmp input files in this PR

Good to know, I will try again.

**Comment by jrgissing** [comment]
> What would be the advantage to have a single periodic CNT? What was the idea behind it?

Here are my thoughts: These CNTs are too short to be physically realistic (even ultra-short CNTs are tens of nms). Also, I am used to seeing significant degrees of polymerization. Without that, I do not think the usefulness of the method gets across. I think the high packing fraction of the CNTs, small system, and long monomer units are mostly to blame (along with short run time, which we can't really get around for a tutorial). So, I am thinking that a single CNT with higher percentage of smaller monomers might do the trick. For example, we could try polystyrene. 

For analysis, perhaps in a separate tutorial or add-on section, we could look at inclusion energy by comparing energy of composite with sum of energies of neat polymer and lone CNT.

I can take a first pass at these updates, if you agree with them. Please let me know what you think.

**Comment by simongravelle** [comment]
> These CNTs are too short to be physically realistic

I don't think that the realism of the system should be a big concern here, since the goal is for the users to learn something new about LAMMPS compared to the previous tutorial.

- With a single periodic CNT, the system is more difficult to equilibrate due to the anisotropy of the system, which is may be completely fine if that's something we think is meaningful for the user to learn, and would indeed be a novelty compared to the previous tutorials.
- With small multiple CNTs, the system is easier to equilibrate but may offer more possibilities for the analysis. I am fine with both.

@akohlmey Do you have a strong argument against one or the other?

**Comment by akohlmey** [comment]
> @akohlmey Do you have a strong argument against one or the other?

Not really. If explained properly, I see a small benefit in the option to go with a single periodic CNT and discussing the benefits and limitations of such a setup.

**Comment by simongravelle** [comment]
OK, OK, let's do a single CNT then. :)

**Comment by jrgissing** [comment]
@simongravelle do you want to merge this branch, and I will take a pass at a single periodic CNT and using polystyrene as matrix?

**Comment by simongravelle** [comment]
> @simongravelle do you want to merge this branch, and I will take a pass at a single periodic CNT and using polystyrene as matrix?

Its up to you. I've let it open in case you want to work from there, but it can be merged.

**Pull request merged**
