### PR TITLE
Work on the appendix

### PR DESCRIPTION
**Pull request by simongravelle**
- small rewriting of existing appendixes

### CODE REVIEW

**Comment by simongravelle** [comment]
Hi @akohlmey,

To fill in some of the missing sections in the Appendix, I heavily copy-pasted content from there : https://docs.lammps.org/Howto_lammps_gui.html. Please let me know if its not OK.  I assumed that it was written by you, and so that its probably OK to duplicate it here. 

Simon

**Comment by akohlmey** [comment]
> I assumed that it was written by you, and so that its probably OK to duplicate it here.

@simongravelle you are correct on both counts.

**Comment by akohlmey** [comment]
@simongravelle I added a couple of small corrections. Since we document flatpak bundles I also created them for the latest release and stable update and uploaded them to GitHub.

**Comment by simongravelle** [comment]
There are 2 remaining sections to be filled:

- Compiling LAMMPS from Source on Linux
- Running LAMMPS in Parallel with MPI

Given that the tutorials now focus 100% on the LAMMPS-GUI using precompiled LAMMPS version, I wonder if this is really the place to write about compiling and MPI. In addition, given that the documentation will always be the best place to find such information, I don't know how much of the doc we should replicate here, @akohlmey ? I can try writing a first draft if its something that you think should be there.

To me, something along the line of "LAMMPS can also be launched 100% from command line without GUI, and this is how you do it" could be enough.

**Comment by akohlmey** [comment]
> To me, something along the line of "LAMMPS can also be launched 100% from command line without GUI, and this is how you do it" could be enough.

I agree with this. A step-by-step beginner's guide for compiling LAMMPS would be a separate tutorial and the same goes for running LAMMPS in parallel with MPI (on a cluster), which would best be combined with a tutorial on benchmarking and how to optimize performance through: using the processors command, optimizing MPI vs OpenMP distribution of processor cores, balance and fix balance, different neighbor list settings, cutoffs for long-range Coulomb and much more.

**Comment by simongravelle** [comment]
@akohlmey I can merge that one, unless you prefer to correct the appendix directly from this PR.

**Review by akohlmey — APPROVED** [review]
I currently have no time to work on this properly.

**Comment by simongravelle** [comment]
> I currently have no time to work on this properly.

No problem at all, I will merge for now to avoid future git conflict.

**Pull request merged**
