### PR TITLE
test tutorials

### PR DESCRIPTION
**Pull request by simongravelle**
I am following all 8 tutorials as if I were a user, and correct some sentence/file/figure along the way.

### CODE REVIEW

**Comment by simongravelle** [comment]
@akohlmey , some though about the GUI. First of all, for the most part, it works beautifuly. 

1) when finishing the setup, there is an extra step that feels unecessary (click on the finish ...) --> that really makes the whole "setting up" process feels long as one have to click next 4 times, I would remove if possible.

2) when downloading tutorial 1 with solution, from my home where the wifi is not as good as at the Univ, it takes time, and while its loading the GUI behaves like it has just crashed. I see several solutions:
  - indicate that download is in progress (a progress bar? the name of the file currently being dowloaded?), so the user knows it did not crash
  - indicate the size of the solution next to the "download solution" button so people can anticipate this delay
  - have the solution getting downloaded in the background while the non-solution file are already fully operational
  - reduce the size of the solution by not putting video files at all, or by putting videos in another folder (and as another box to be checked)


3) I would may be remove the LAMMPS tutorial logo from the step wizard, it does not go very well alongside the tutorials' picture. I am also in the process of creating a representative image for the journal, so may be this will end up looking better than the current one:

lammps-tutorials

or may be the T logo could work better:

logo

(but it would have to be much smaller than the tutorial image)

**Comment by akohlmey** [comment]
> @akohlmey , some though about the GUI. First of all, for the most part, it works beautifuly.
> 
> 1. when finishing the setup, there is an extra step that feels unecessary (click on the finish ...) --> that really makes the whole "setting up" process feels long as one have to click next 4 times, I would remove if possible.

For that matter, the first page would also be redundant and could be merged with the second.
Originally, I had expected to have more steps, but there really is only the selection of the directory and whether to download the solution files.

> 2. when downloading tutorial 1 with solution, from my home where the wifi is not as good as at the Univ, it takes time, and while its loading the GUI behaves like it has just crashed. I see several solutions:
> 
> * indicate that download is in progress (a progress bar? the name of the file currently being dowloaded?), so the user knows it did not crash
> * indicate the size of the solution next to the "download solution" button so people can anticipate this delay
> * have the solution getting downloaded in the background while the non-solution file are already fully operational
> * reduce the size of the solution by not putting video files at all, or by putting videos in another folder (and as another box to be checked)

I will have to have a look at what can be done in the GUI. Some indication of what is going on would certainly be useful.
Showing the download size, would require an addition to the metadata file, so a text of the kind "downloading file x of y" and/or a progress bar, should be helpful.

> 3. I would may be remove the LAMMPS tutorial logo from the step wizard, it does not go very well alongside the tutorials' picture. May be the T logo in LAMMPS-style could work better (but it would have to be much smaller than the tutorial image):

At the moment, I don't want to do that, since the master plan is to also support the tutorials from here: https://github.com/mrkllntschpp/lammps-tutorials

Or, in a second step, those could be added (with permission from Mark) where they cover topics not currently covered.
These are also well matured tutorials that have helped a lot of LAMMPS users to get started.

I don't like the "T" logo that much. It serves well as the icon for menu entries and windows, but not much more.
At the moment, I want to focus on the programming and the text. Tweaking the graphics can be done later.
Personally, I prefer more vibrant colors rather than pastel-like colors. Makes things look more "active".
But: functionality first, all style later.

BTW, I am still looking for a good idea:
The output window now will highlight errors and warnings in a bold red text (when scrolling around, those stand out quite well), but since the output usually scrolls fast, it may not be easily visible. Do you have an idea how it could be best indicated that there are warnings? My thoughts so far:
- modify title text (append " - 3 Warnings" or something similar)
- have some button added (Jump to next Warning) that is faded and inactive by default and becomes active when the first warning shows up
- have a split view where the added view shows *only* warnings/errors (a bit like Visual Studio does it). But then the question is: should this be configurable?, or always on? The downside is that the warnings are missing the context in the warnings-only view.

Neither of those ideas seem satisfactory to entice users to have a look and make efficient use of the screen real estate.

**Comment by simongravelle** [comment]
> BTW, I am still looking for a good idea: The output window now will highlight errors and warnings in a bold red text (when scrolling around, those stand out quite well), but since the output usually scrolls fast, it may not be easily visible. Do you have an idea how it could be best indicated that there are warnings? My thoughts so far:
> 
>     * modify title text (append " - 3 Warnings" or something similar)
> 
>     * have some button added (Jump to next Warning) that is faded and inactive by default and becomes active when the first warning shows up
> 
>     * have a split view where the added view shows _only_ warnings/errors (a bit like Visual Studio does it). But then the question is: should this be configurable?, or always on? The downside is that the warnings are missing the context in the warnings-only view.
> 
> 
> Neither of those ideas seem satisfactory to entice users to have a look and make efficient use of the screen real estate.

I definitely like the red warning.

Among the 3 propositions,  I like the ''Jump to next Warning" button the most, as they can be hidden in a long log file.

**Comment by simongravelle** [comment]
> At the moment, I don't want to do that, since the master plan is to also support the tutorials from here: https://github.com/mrkllntschpp/lammps-tutorials

no problem (in that case, the official LAMMPS logo could also be a good option)

**Comment by akohlmey** [comment]
@simongravelle I've produced new LAMMPS-GUI binaries.
- All tutorials should now have a matching introduction text adapted from the intro of the paper.
- The tutorial wizards are reduced to two pages.
- When clicking "Finish" the wizard dialog is closed immediately and then the main window status message area and progress bar are used to indicate the download status (same as during a run). The "Ready." text is replaced with "Downloading file X of Y". This is on a per-file basis.
- There is now a panel display of the number of warnings/errors and total number of lines in the output buffer and a push button on the right to jump to the next warning/error (see image)
lammps-gui-log

**Comment by simongravelle** [comment]
Hi @akohlmey, this is getting better and better. I like the new changes.

I've just noticed something strange, that you can reproduce by running the mixing.lmp file of tutorial 8 (use that one because the current file in solution is incorrect):

```

units real
boundary p p p
atom_style full

kspace_style pppm 1.0e-5
pair_style lj/class2/coul/long 8.5
angle_style class2
bond_style class2
dihedral_style class2
improper_style class2

pair_modify tail yes mix sixthpower
special_bonds lj/coul 0 0 1

units real
boundary p p p
atom_style full

kspace_style pppm 1.0e-5
pair_style lj/class2/coul/long 8.5
angle_style class2
bond_style class2
dihedral_style class2
improper_style class2

pair_modify tail yes mix sixthpower
special_bonds lj/coul 0 0 1

read_data CNT.data extra/special/per/atom 20

molecule styrene styrene.mol
create_atoms 0 random 200 8305 NULL overlap 2.75 &
   maxtry 500 mol styrene 7687

minimize 1.0e-4 1.0e-6 100 1000
reset_timestep 0

velocity all create 530 9845 dist gaussian rot yes
fix mynvt all nvt temp 530 530 100
fix mydef all deform 1 y erate -0.0001 z erate -0.0001
variable rho equal density
fix myhal all halt 10 v_rho > 0.9 error continue
thermo 200
thermo_style custom step temp pe etotal press density
run 9000

dump viz all image 200 myimage-*.ppm &
type type shiny 0.1 box no 0.01 size 1000 1000 &
view 90 0 zoom 1.8 fsaa yes bond atom 0.5
dump_modify viz backcolor white &
acolor cp gray acolor c=1 gray &
acolor c= gray acolor c1 deeppink &
acolor c2 deeppink acolor c3 deeppink &
adiam cp 0.3 adiam c=1 0.3 &
adiam c= 0.3 adiam c1 0.3 &
adiam c2 0.3 adiam c3 0.3 &
acolor hc white adiam hc 0.15

unfix mydef
unfix myhal
reset_timestep 0

group CNT molecule 1 2 3
fix myrec CNT recenter NULL 0 0 units box shift all

run 10000

write_data mixing.data

``` 

When I launch the simulation, but click on "stop" in the middle of the first run, the GUI does not stop, instead it jumps to the next run. I am using the [LAMMPS-Linux-x86_64-GUI-29Aug2024_update2_test.tar.gz](https://download.lammps.org/testing/LAMMPS-Linux-x86_64-GUI-29Aug2024_update2_test.tar.gz) version.

**Comment by simongravelle** [comment]
Another issue is that when I try to run the downloaded solution directly, I get message like :

image

The file in question, here for instance *parameters.inc* from tutorial 3, was initially a symbolic link. It seems that the symbolic link was destroyed in the process. If I type 

`cat parameters.inc`

from the *downloaded* solution folder of tutorial 3, I get:

`../parameters.inc`

I note that when running LAMMPS directly from the "files/tutorial3/solution" from the Git repository, I don't get that error.

When looking more to the downloaded file, I notived that if I check the file content of

**Comment by simongravelle** [comment]
@akohlmey Another minor issue. When running the GUI, for instance running relax.lmp from the solution folder of tutorial 5, the number of Warning found by the GUI is 5, but I can only see 4 warning when scrolling the entire log:

image

**Comment by akohlmey** [comment]
> @akohlmey Another minor issue. When running the GUI, for instance running relax.lmp from the solution folder of tutorial 5, the number of Warning found by the GUI is 5, but I can only see 4 warning when scrolling the entire log:

I can confirm this. For efficiency reasons, the counting of the warnings is done together with the highlighting. Apparently some line is highlighted twice and thus the warning count too high. I have to think about an alternative. I don't want to search the entire text buffer for every update as that would have a significant negative performance impact for runs with lots of output and the cost would grow quadratically with the amount of output.

Perhaps there is a way to search the text buffer *before* it is appended. Or instead of giving the number of warnings there could just be a statement "Output has warning or error messages" and "Output has NO warning or error messages". On the other hand, I can live with a glitch where warnings are in rare cases counted multiple times. The important fact is the yes/no property. The jump to next warning functionality only checks for that.

**Comment by akohlmey** [comment]
> The easy solution is to remove all symbolic links and duplicate all file instead. But may be you know a way to preserve the symbolic links?

Not a good solution. Symbolic links ensure consistency.

I had been assuming that the download would download a copy and not a file with the reference.
This is worth investing significant effort, since this needs a special solution for Windows which has no symbolic links.

**Comment by simongravelle** [comment]
> I can live with a glitch where warnings are in rare cases counted multiple times

I agree, this is really a minor issue.

**Comment by akohlmey** [comment]
> > I can live with a glitch where warnings are in rare cases counted multiple times
> 
> I agree, this is really a minor issue.

It may actually be interesting to see, if somebody else would spot this *and* report it.

I am still shaken by the observation that neither I nor somebody else had noticed that there was no "find" and "find / replace" functionality in LAMMPS-GUI for more than a year.

**Comment by akohlmey** [comment]
@simongravelle I think I have a sufficiently portable solution for downloading the symbolic link files. I've applied a few more small tweaks and polishes to the code and made new test binaries and uploaded them.

I plan to review all tutorials myself next (unless you find me more things to do for LAMMPS-GUI, I have collected some general ideas here, but those have not been implemented for a variety of reasons, I am happy to add more, specifically, if they can be implemented more easily): https://github.com/lammps/lammps/blob/8b32516b793602c93446e3adba6ca60cf3eb7ae2/tools/lammps-gui/TODO.md

I will create a pull request and then work my way through the paper. I already found one issue. In the .manifest files, the symlink targets have to be listed before the symlinks (in the repo), since I cannot copy what isn't there yet.

I have about a week's worth of time left until I have to switch back to focus in Temple stuff and want to give the tutorial precedence over other LAMMPS stuff.

**Comment by simongravelle** [comment]
> I have about a week's worth of time left until I have to switch back to focus in Temple stuff and want to give the tutorial precedence over other LAMMPS stuff.

Good to hear. I will also be available and can review the PR asap.

Currently, I only have two things on my todo list for the article, i.e., the issues I raised yesterday (deal with the warning in tutorial 4 about using fix nve/limit and shake -- I think the best solution is to not use fix nve/limit -- and add an annexe about dump atom).

**Pull request merged**
