### PR TITLE
Homogenize and clean tutorial 2

### PR DESCRIPTION
**Pull request by simongravelle**
- use \guicmd and \lmpcmd consistently in tutorial 2
- replaced Berendsen by nose-hoover (for central group)
- remove variable T in inputs
- removed extra space in inputs
- use Axel's representation for the CNT instead of the spheres
- considerably simplified part B, breakable (because most of it is duplicate of part A, unbreakable)
- increased the speed of the deformation in part B to reduce the computational cost
- added symbolic links to avoid duplicating some files

image

### CODE REVIEW

**Comment by simongravelle** [comment]
Issues:

- the variable Lcnt (formely L) is not updated in the GUI... I can't figure out why. I tried different names for the variable, different definition for Lcnt, different combinations for the thermo_style...

image

**Comment by simongravelle** [comment]
Its a small thing, but now the tutorial2/solution folder contain some files that are within tutorial2, such as parameters.inc. 

If we remove the parameters.inc from the tutorial2/solution folder, then the lammps input cannot be executed directly from  tutorial2/solution.

If we remove the parameters.inc from tutorial2 folder, its going to mess up the setting up of the simulation. 

@akohlmey, did you have something better in mind? Or do we accept that some files will be duplicated? Its not a huge deal, but of course it increases the chance of having future inconsistencies...

**Comment by akohlmey** [comment]
> @akohlmey, did you have something better in mind? Or do we accept that some files will be duplicated? Its not a huge deal, but of course it increases the chance of having future inconsistencies...

You could make the duplicated entries in the solution folder symbolic links to the corresponding files in the  '..' folder and thus minimize the risk of inconsistencies.

**Comment by simongravelle** [comment]
> You could make the duplicated entries in the solution folder symbolic links to the corresponding files in the '..' folder and thus minimize the risk of inconsistencies.

Yes! That would work. Perfect, thanks, I will try that.

**Comment by simongravelle** [comment]
If you feel like I am using too many "note", please let me know:

image

**Comment by simongravelle** [comment]
@akohlmey before I merge, I would like your opinion on 2 things:

1)  I did not include your tip to display bond with AIREBO force field within the main tutorial, but only as an extra tip at the end of the tutorial. Is it what you had in mind?

2) The GUI does not show the variation of the CNT length (for neither unbreakable or breakable)... I can't figure out why, do you have an idea?

**Comment by akohlmey** [comment]
> @akohlmey before I merge, I would like your opinion on 2 things:
> 
> 1. I did not include your tip to display bond with AIREBO force field within the main tutorial, but only as an extra tip at the end of the tutorial. Is it what you had in mind?

Yes. It is a rather elaborate hack and should eventually become obsolete, if I convince Steve to help me implement a proper solution: https://github.com/lammps/lammps/issues/4268

> 2. The GUI does not show the variation of the CNT length (for neither unbreakable or breakable)... I can't figure out why, do you have an idea?

This is (another) failure of the empirical code I've experimented with to drop outliers from the thermo data graphs. I am removing this now and will have to implement some kind of locking to avoid modifications of the cached thermo data while it is being read.

**Comment by akohlmey** [comment]
I've made a temporary version of the current LAMMPS-GUI code and uploaded it to https://download.lammps.org/testing/LAMMPS_GUI-Linux-amd64-29Aug2024.tar.gz
This will use the new download location for the tutorial files and has the outlier hack removed.

**Review by akohlmey — APPROVED** [review]

**Pull request merged**
