### PR TITLE
Continue type labels update

### PR DESCRIPTION
**Pull request by jrgissing**
- [x] finish type label update for tutorials 3.4-7

~~looks like 'dump image' type label support needs to be added~~

### CODE REVIEW

**Comment by jrgissing** [comment]
I like Axel's idea of an eighth tutorial that utilizes 'fix bond/react'. @simongravelle if you agree, I can start drafting that

**Comment by simongravelle** [comment]
> I like Axel's idea of an eighth tutorial that utilizes 'fix bond/react'. @simongravelle if you agree, I can start drafting that

Yes of course, it would be great to have a bond/react tutorial. Do you have an idea of the system it could be?

**Comment by jrgissing** [comment]
> > I like Axel's idea of an eighth tutorial that utilizes 'fix bond/react'. @simongravelle if you agree, I can start drafting that
> 
> Yes of course, it would be great to have a bond/react tutorial. Do you have an idea of the system it could be?

Good question. The simplest from my perspective would be to use one of the existing examples shipped with lammps, such as polymerization of a polyamide

**Comment by simongravelle** [comment]
> Good question. The simplest from my perspective would be to use one of the existing examples shipped with lammps, such as polymerization of a polyamide

OK OK that would work. Something to keep in mind: for tutorials, when possible, it is best to keep the computational cost as low as possible, with either a small system and/or short simulation time.

Another thing, since its tutorial n°8, and users will be familiar with LAMMPS by then, I think that we shouln't hesitate to use a more complicated system, for instance with two molecules types, or with a CNTs loaded into the polymer matrix (a system that seems to be popular with beginners). Of course we should do that only if we think that it makes sense and could make the tutorial more interesting, for instance by allowing us to illustrate the use of some interesting compute/fix that are not used in tutorials 1-7. Its even better when we can imitate some cool publications, like is done in tutorial 3.

If you have the files for the polymer with the type labels, I am also happy to draft the first version, or you can do it, as you prefer.

**Comment by jrgissing** [comment]
The simplest polyamide (PA) example shipped with lammps has just the two co-monomers for PA (example name: tiny_nylon). There is also an example with a box full of monomers with ~35K atom (example name: nylon,6-6_melt). All examples have already been converted to type labels. It could be interesting to polymerize around a CNT though (that was one of original motivations for bond/react). I am still working through some things for the lammps stable release, so if you start the tutorial just let me know when you are ready for me to chip in.

**Comment by jrgissing** [comment]
Yes, it should probably be PCFF to be consistent with the polymer. Please let me know if you would like me to build a PCFF CNT.

**Comment by simongravelle** [comment]
> Yes, it should probably be PCFF to be consistent with the polymer. Please let me know if you would like me to build a PCFF CNT.

If this is something that you know how to generate without too much effort, then yes, it would be super helpful to me...

**Comment by jrgissing** [comment]
okay, this completes my first pass at adding type labels to tutorials 3.4-7

**Review by simongravelle — APPROVED** [review]
Seems good to me. I did not re-test all the tutorials, but we can do it as we revise the tutorials.

**Pull request merged**
