### PR TITLE
started making tutorial 5 GUI

### PR DESCRIPTION
**Pull request by simongravelle**
- wrap lines
- changed .lammps to .lmp files
- use dump image more systematically
- added python script for reading dump file

### CODE REVIEW

**Comment by simongravelle** [comment]
Hi Axel @akohlmey,

I've noticed a small trouble with the GUI. When the third input file from tutorial 5 (the Decorate part) is executed using the GUI, it crashes after the end of the first loop with the error message: 

> LAMMPS (27 Jun 2024)
>   using 64 OpenMP thread(s) per MPI task
> set 1 OpenMP thread(s) per MPI task
> using multi-threaded neighbor list subroutines
> terminate called after throwing an instance of 'LAMMPS_NS::LAMMPSAbortException'
>   what():  ERROR on proc 0: step 2000: hbondchk failed: H=0 end(H)=30 str(H+1)=25
>  (src/OPENMP/reaxff_forces_omp.cpp:209)
> Last command: run             2000
> Aborted (core dumped)

The same error occurs regardless of the number of threads I request.

However, if I run the same input without the GUI, it works just fine.  In both cases, I used the precompiled versions of LAMMPS GUI-1.6.3 (either the lmp or the lammps-gui executable).

I join the zip file with the current inputs from tutorial 5, if you are interested: [core-dumped-tutorial5.zip](https://github.com/user-attachments/files/16373904/core-dumped-tutorial5.zip)

Simon

**Comment by akohlmey** [comment]
> However, if I run the same input without the GUI, it works just fine.

What is your command line when running on the console? Does it also enable threads?
When I run with `OMP_NUM_THREADS=16 ./lmp -in  input.lmp -sf omp` I get the same crash with hbondchk as you report.
When I run in the GUI with OpenMP threading turned off in the preferences for accelerators, I do not see a crash.
no-crash


The logical conclusion from that is that this would rather be a bug in the OpenMP version of ReaxFF and not the GUI.

**Comment by akohlmey** [comment]
@simongravelle I think I have found and fixed the bug in the ReaxFF OpenMP version.

**Comment by simongravelle** [comment]
ps: I just saw your message, those are the tests I was currently performing, but I guess this can be ignored now.

> What is your command line when running on the console? Does it also enable threads?

**LAMMPS GUI-1.6.3**

I was simply using

`./lmp -in input.lmp`

When I use 

`OMP_NUM_THREADS=16 ./lmp -in  input.lmp -sf omp`

I indeed also get the error. 

**27Jun2024**

The command:

`mpirun -np 16 ./lmp_mpi -in input.lmp`

 works fine too, but 

`OMP_NUM_THREADS=16 ./lmp_mpi -in input.lmp -sf omp`

return the same error.

> The logical conclusion from that is that this would rather be a bug in the OpenMP version of ReaxFF and not the GUI.

Indeed. I can create an issue on the GitHub repository of LAMMPS, if you think that this is appropriate. I will provide a minimum input.

**Comment by akohlmey** [comment]
@simongravelle I've updated the binary packages with the bugfix. Please check it out.

**Comment by simongravelle** [comment]
> @simongravelle I've updated the binary packages with the bugfix. Please check it out.

Works just fine

**Pull request merged**
