### PR TITLE
Small aesthetic changes

### PR DESCRIPTION
**Pull request by simongravelle**
- changed the style of the LAMMPS code (It used to be bold text inside a gray block with a dark line):

image

### CODE REVIEW

**Comment by simongravelle** [comment]
@akohlmey are you ok with this new style? I did not like the previous bold style so much, with that font it looked weird ...

**Comment by akohlmey** [comment]
> @akohlmey are you ok with this new style? I did not like the previous bold style so much, with that font it looked weird ...

Yeah, fine with me.

Perhaps quoted commands should use the same style then or something more similar. Right now they use a monospace font and dark gray on light gray to make them stand out less.

**Comment by simongravelle** [comment]
True. I can modify that too.

**Comment by simongravelle** [comment]
Having gray boxes everywhere was a bit much, so I tried a relatively discrete style for the files (same for the folder, but folders will probably all disappear when tutorials are being homogenized):

image

Now, all the different styles can be adjusted from the beginning of the tex file:

```
\renewcommand{\emph}[1]{\underline{#1}} % make \emph{} use underline instead of italic
\newcommand{\lmpcmd}[1]{\hspace{0pt}\colorbox{listing}{\textcolor{command}{\texttt{#1}}}\hspace{0pt}} % lammps command
\newcommand{\flrcmd}[1]{\textcolor{command}{\texttt{#1}}} % folder
\newcommand{\flecmd}[1]{\textcolor{command}{\texttt{#1}}} % files name 
\newcommand{\dwlcmd}[1]{\textcolor{download}{\texttt{#1}}} % downloadable files
```

**Pull request merged**
