### PR TITLE
Homogenize and clean tutorial 3

### PR DESCRIPTION
**Pull request by simongravelle**
- fixed files and added a manifest
- implemented a measurement of the dihedral angle instead of the end to end distance (which was too similar to the gyration radius measurement)
- use kspace ewald instead of pppm (I think its nice to use ewald at least once, and pppm is already used in the following tutorials)
- used a smaller PEG molecule --> and less water molecules (the tutorial was computationally expensive)
- use write_restart instead of write_data
- tried a less aggressive color for the notes:

image

### CODE REVIEW

**Comment by simongravelle** [comment]
I am considered using write_restart for this tutorial instead of write_data, for variety.

@akohlmey, any preferred suffix for restart files? `.res`? `.bin` ?

**Comment by akohlmey** [comment]
> @akohlmey, any preferred suffix for restart files? `.res`? `.bin` ?

There is no fixed convention, but most common is either restart.\<name\> or \<name\>.restart and then variants with the embedded timestep number. I've also seen .rest.

Both '.res' and '.bin' are suboptimal choices. ".res" is commonly used for "resource files" that embed icons, images and similar into executables (mostly on Windows though) and ".bin" is the suffix to change LAMMPS native dump files from text mode to binary mode.

**Comment by simongravelle** [comment]
> There is no fixed convention, but most common is either restart.<name> or <name>.restart and then variants with the embedded timestep number. I've also seen .rest.

OK. `.restart` seems fine to me.

**Comment by simongravelle** [comment]
I am not using binary restarts usually, so I am just now discovering that `.restart` files do not store `kspace_style`. Therefore, the second run starts with the following strange input:

image

I can see that this is a documented behavior, but I was wondering is there was a reason for that, or if it was just never implemented?

I note that this is not a problem for the tutorial, on the contrary, it is a good opportunity to warn the users that not everything is stored in the .restart file.

**Comment by simongravelle** [comment]
@akohlmey @jrgissing  I am planning to merge that one, if you don't have no objection.

If you know a method to extract histograms for a certain type of dihedral (cf my previous comment on here), I am interested.

**Comment by akohlmey** [comment]
> * use kspace ewald instead of pppm (I think its nice to use ewald at least once, and pppm is already used in the following tutorials)

kspace ewald doubles execution time for this example. It is best used for tiny and sparse systems, since ewald scales O(N^{2/3}) with the number of particles while pppm scales O(N*log(N)) with the volume (due to the FFTs over grid points).

You could do an initial run with ewald and then switch to pppm (since they are compatible) for improved speed.

**Comment by akohlmey** [comment]
> If you know a method to extract histograms for a certain type of dihedral (cf my previous comment on here), I am interested.

I cannot think of a way since LAMMPS doesn't have "local" style variables and while compute dihedral/local can do some computation using internal and equal style variables, there is no access to the dihedral type for that computation. This would have to be programmed into the compute (and equivalent for the other local computes).

I am busy with some upgrades to the Temple Jenkins cluster and testing scripts currently and probably would need to discuss the details first with Steve.
My recommendation is to submit a feature request issue on the LAMMPS GitHub repo.

**Pull request merged**
