### PR TITLE
Make tutorial 1 GUI-only

### PR DESCRIPTION
**Pull request by simongravelle**
Here, the tutorial 1 is being converted into GUI only. Most likely, the tutorial is still not using enough the possibilities of the GUI tool, so please let me know if you have suggestion of additional feature that could be displayed (like the variables info)?

Also, there are some points on which I would like your opinion:

### Concerning the _2.2 Software/system requirements_ section

What is the best way to instruct people to install lammps with the GUI? The LAMMPS webpage of the GUI advises the user to download a precomplied LAMMPS version, and the "make install" page does not refer to GUI at all, so I suppose it is complicated to install manually? Should we advise the CMake way? Should we only suggest the precompiled version (and in this case, is it really necessary to specify the packages?)

### A weird behavior about the GUI 

I've noticed, following the current tutorial 1, (see for instance the WARNING in red in the text), that if I only run the minimization energy step, the GUI opens by default on the total energy, but the graph is empty. Moreover, I can't switch to the other quantities using "select data". After I add part B to the script and run the MD step as well as the energy minimization, then it seems to work just fine, i.e. I can switch from the temperature to the other quantities, and there is data in the graph (it happens with both 27Jun2024 and 2Aug2023 precompiled linux version). Is it because the minimization energy does not have enough steps?

### A mildly annoying aspect of the graphs generated by the GUI

The first data point at step = 0 is not shown on the graph, and the last point is always 0.

image

image

## In my TODO list

- <del>Use the dump image command instead of VMD, because currently the vizualisation part does not use the GUI enough.</del> (DONE) 
- <del>The VMD part was pushed to tutorial 2.</del> (DONE)

### CODE REVIEW

**Comment by akohlmey** [comment]
> What is the best way to instruct people to install lammps with the GUI? The LAMMPS webpage of the GUI advises the user to download a precomplied LAMMPS version, and the "make install" page does not refer to GUI at all, so I suppose it is complicated to install manually? Should we advise the CMake way? Should we only suggest the precompiled version (and in this case, is it really necessary to specify the packages?)

The experience from the tutorial day at past LAMMPS user workshops (in person and virtual) over many years has been that starting with having people to compile LAMMPS adds a huge burden at the beginning, consumes a lot of time, and can be quite challenging for today's beginners since their proficiency in compiling from source is generally very limited. Add to that, that compiling on macOS can be challenging and installing the necessary tools time consuming and on Windows the situation is even worse: only very recently has MS visual studio become available free of cost and installing cygwin is a major task that requires using a unix-like environment on windows.

Thus we had initially chosen to provide a precompiled version of LAMMPS in a VirtualBox container for x86_64, which worked for almost everybody at the last in-person tutorial, but with Apple switching to ARM based CPUs that was no longer viable. Thus we came up with having precompiled binaries packaged in a way that they can be run on most platforms: Windows installer packages, macOS .dmg app installer images (with executables containing code for both x86_64 and apple CPUs), Linux binaries bundled with wrapper scripts and required shared libraries, so they can run on a wide range of x86_64 (anything at the level of Ubuntu 20.04LTS or more recent). The 2023 tutorial was text mode only and this year we adapted everything for LAMMPS-GUI. The LAMMPS-GUI binary in the stable release is missing a lot of features and bugfixes since the more recent code depends on features only available in the release branch.

My perspective is the following:
- get started with the GUI so there is only one program to learn and no operations on the console required
- keep using the GUI as text editor unless you have a different preference
- The packages with the GUI also contain the regular console mode LAMMPS binary "lmp" so no compilation should be needed. The linux platform is the most fragile, but the `lammps-linux-x86_64-<version>.tar.gz` package contains a statically linked console binary that will run on pretty much *any* Linux x86_64 platform (we tested as old as Ubuntu 16.04LTS).
- Compilation from source is generally required for running in parallel with MPI, so I would suggest to make that a "bonus" tutorial at the end of the paper where then also some explanations for running in parallel are given. This is complicated a bit these days for people running on HPC clusters that use SLURM since that comes with a wrapper for mpirun/mpiexec.
- The precompiled packages do include OPENMP, GPU (using OpenCL) and KOKKOS/OpenMP where possible, so it can run in parallel where supported. In the GUI this is chosen in the Preferences dialog.

My impression is that this is the path most accessible to people looking for an introductory tutorial.

**Comment by akohlmey** [comment]
> and the "make install" page does not refer to GUI at all,

"make install" is CMake only and was added by and for people that do packaging of LAMMPS for distributions. Most of its functionality is thus "unofficial" and can change at any time.

Compiling LAMMPS-GUI from source is significantly more complex than LAMMPS itself, since it requires the Qt toolkit and its development headers and there may be some tweaking of the CMake configuration required to have it find the headers and libraries. So definitely not something to burden beginners with.

**Comment by akohlmey** [comment]
> ### A weird behavior about the GUI
> I've noticed, following the current tutorial 1, (see for instance the WARNING in red in the text), that if I only run the minimization energy step, the GUI opens by default on the total energy, but the graph is empty. Moreover, I can't switch to the other quantities using "select data". After I add part B to the script and run the MD step as well as the energy minimization, then it seems to work just fine, i.e. I can switch from the temperature to the other quantities, and there is data in the graph (it happens with both 27Jun2024 and 2Aug2023 precompiled linux version). Is it because the minimization energy does not have enough steps?

I have to explain a bit more in detail the mechanism how the GUI "harvests" the thermo data. LAMMPS itself doesn't know anything about it since it is running independently in a separate thread. For some other use within LAMMPS we added a feature that any thermodynamic output is cached and can later be retrieved through a function call. For LAMMPS-GUI we exposed this call also to the library interface. During a run, the GUI is polling the LAMMPS instance for thermo data. This works because threads share the address space. This is done by default at a 100ms interval to reduce overhead of using the GUI. That will fail to pick up data fast enough, if the simulated system is small and the output not frequent enough or both. This has been reported as a problem for tutorials before and in response I have made the polling interval adjustable in the preferences dialog.

There are 3 ways that the situation can be improved:
- make the system larger
- have more frequent thermo output
- reduce the polling delay from the default 100ms. Lower limit is 1ms.

**Comment by simongravelle** [comment]
Thank you, Axel, for your insights.

- Reducing the GUI update time interval works fine for tutorial 1, so we can go with that.  
- I agree that not bothering new users with compiling LAMMPS makes it easier, so maybe the only instruction at the beginning of the article could be "download the corresponding precomplied LAMMPS-GUI" and not talk at all about the packages.  Then I also agree that we could make all 7 tutorials with the GUI (if it works, I did not try that yet). Having some additional instruction for running LAMMPS on a cluster would indeed be a nice final supplement (right now the article finishes a bit abruptly, without ccl or final remark, so it would be nice to have some final notes and comments)

> The LAMMPS-GUI binary in the stable release is missing a lot of features and bugfixes since the more recent code depends on features only available in the release branch.

I initially thought that it was better if the tutorials from the article were made compatible with the last stable version of LAMMPS, instead of a release branch, but since the next stable version is coming soon (as I think you said on the MATSCI forum), we can simply make all tutorials compatible with the 2024 stable version before submitting the article.

Best,
Simon

**Pull request merged**
